# -*- coding: utf-8 -*-
"""Data Mining - preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10v-vjPDhBMRHsuAUUVdPz5azXjlD2Yc6

#Tugas Praktikum Data Mining - Preprocessing
## Nama: Izza Rizkya Az-Zahra
## NIM: 4112322001
## Prodi: Statistika Terapan dan Komputasi

# **1. MEMUAT DATA**

Import Library yang digunakanan
"""

import pandas as pd
# Memuat data dari file CSV
df = pd.read_csv('Automobile_data.csv')
# Menampilkan 5 baris pertama dari dataset
df.head()

"""Muat Data Movie dari github"""

!wget https://github.com/izzazhraa/Data-Mining/blob/main/movie_sample_dataset.csv

"""Masukkan ke dalam data frame"""

import pandas as np
movdf = pd.read_csv("movie_sample_dataset.csv")
movdf

"""# **2. MEMERIKSA DATA**

Memeriksa Tipe data dan Data yang Hilang
"""

movdf.info()

print(movdf.isnull().sum())

"""# **3. MEMBERSIHKAN DATA**"""

movdf.loc[:, 'color'] = movdf['color'].str.strip().str.capitalize()
movdf.loc[:, 'country'] = movdf['country'].str.strip().str.upper()
movdf = movdf[(movdf['duration']>=0)&
              (movdf['gross']>=0)&
              (movdf['title_year']>=0)&
              (movdf['budget']>=0)&
              (movdf['imdb_score']>=0)&
              (movdf['movie_facebook_likes']>=0)]
movdf = movdf.replace('N/A', pd.NA)
movdf.dropna(inplace=True)
movdf

"""Dapat dilihat baris yang memiliki nilai NaN di kolom penting seperti gross dan budget sudah terhapus, nilai yang tidak konsisten atau kesalahan penulisan di kolom, seperti perbedaan antara "Color" dan "color" juga sudah diatasi, dan
nilai-nilai yang tidak standar, seperti nilai negatif atau "N/A" sudah diubah dan dihapus. Hal itu dapat dilihat dengan kode dibawah ini

"""

print(movdf.isnull().sum())

"""# **4. TRANSFORMASI DATA**

Mengecek data
"""

movdf.dtypes

"""Mengubah Tipe Data"""

movdf['gross'] = movdf['gross'].astype('int')
movdf['budget'] = movdf['budget'].astype('int')
movdf.dtypes

"""Normalisasi Text"""

movdf['actors'] = movdf['actors'].str.replace(',', ', ', regex=False)
movdf['genres'] = movdf['genres'].str.replace('|', ', ', regex=False)
movdf

"""# **5. PENYIMPANAN DATA**"""

movdf.to_csv('movie_sample_dataset_cleaned.csv', index=False)